#开发环境
server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: mengyiyouth
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    root: info
    com.mengyi: debug
  file:
    name: log/blog-dev.log

mybatis:
  type-aliases-package: com.mengyi.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
